---

- name: "Playbook: Install Postgres"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role: # Install Postgres
        name: alex.postgres.install
